### PR TITLE
Use JSON to restrict subscriptions

### PR DESCRIPTION
**Pull request by martinthomson**
I know that it's the devil, but JSON is the obvious choice here.

### CODE REVIEW

**Comment by costinm** [comment]
Why would it be obvious ? application/x-www-form-urlencoded or a request parameter ?

**Comment by beverloo** [comment]
It's an obvious choice given the proprietary precedence in the industry.

I can't really judge the appropriateness of using JSON as opposed to an alternative -- this change LGTM assuming it is. Since the UA chooses the PS, there is no need for encryption. JSON provides good extensibility for additional (proprietary) data that may have to be transmitted over this channel.

**Comment by costinm** [comment]
At least it's not xml... I don't mind json - just didn't think it is so obvious.

It does open an important question: will the user be allowed to pass more information to the push service (voluntarily) ? 

But +1 on this change.

**Comment by martinthomson** [comment]
> It does open an important question: will the user be allowed to pass more information to the push service (voluntarily) ?

Probably, but I don't want to think about that just yet :)

**Pull request merged**
