### PR TITLE
Adding a section on additional claims

### LINKED ISSUE #24: VAPID claim should include optional extra data field
As noted in the arguments of #23, there is a need for an "extra data" field which would be used by the parties using the VAPID claims. This data would contain information useful to the publisher of the claim (e.g. the originating server ID, transaction ID, or other possibly VAPID consumer opaque data).

This extra data ("vapid-ext" ?) field would allow consistent, predictable definition rather than a set of 'one-offs' that may be difficult to find or ignored by operators.

### PR DESCRIPTION
**Pull request by martinthomson**
Closes #24

### CODE REVIEW

**Comment by beverloo** [comment]
LGTM, thank you!

Is the addition required because of the following language in 7519?

> Applications using JWTs should define which specific claims they use and when they are required or optional.

**Comment by martinthomson** [comment]
Well, that's a good reason, but #24 is the main reason.  See the discussion leading up to that.

**Comment by beverloo** [comment]
I read the thread and issue; reading JWT, there was nothing prohibiting providing additional fields (aside from that SHOULD), so I was wondering if specifying this is a normative requirement or a good clarification :-).

**Comment by jrconlin** [comment]
If I may, clarification is always good. One should presume that the readers of these specs may not be fully versed in the subtle details of other, reliant specs, so a bit of useful info like this might be very welcome.

**Pull request merged**
